## Final Visualisation is published [here](https://public.flourish.studio/visualisation/11919480/)

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/supermarket-sales/supermarket_sales - Sheet1.csv

In [2]:
df = pd.read_csv('/kaggle/input/supermarket-sales/supermarket_sales - Sheet1.csv')
df['Date'] = pd.to_datetime(df.Date).dt.strftime('%Y-%m-%d')
df.head()

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,2019-01-05,13:08,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,2019-03-08,10:29,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,2019-03-03,13:23,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,2019-01-27,20:33,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2019-02-08,10:37,Ewallet,604.17,4.761905,30.2085,5.3

In [3]:
df[['Branch','City']].value_counts()

Branch  City
A       Yangon       340
B       Mandalay     332
C       Naypyitaw    328
dtype: int64

In [4]:
pv_df = pd.pivot_table(data=df,index=['City','Product line'],columns='Date', values='Total', aggfunc='sum')
pv_df.fillna(0, inplace=True)
pv_df = pv_df.reset_index()
pv_df.head()

Date,City,Product line,2019-01-01,2019-01-02,2019-01-03,2019-01-04,2019-01-05,2019-01-06,2019-01-07,2019-01-08,...,2019-03-21,2019-03-22,2019-03-23,2019-03-24,2019-03-25,2019-03-26,2019-03-27,2019-03-28,2019-03-29,2019-03-30
0,Mandalay,Electronic accessories,470.673,138.6630,0.000,75.7785,0.000,0.0000,0.0000,0.000,...,0.0,0.000,0.000,0.000,222.138,143.9865,116.9070,0.0000,0.000,0.000
1,Mandalay,Fashion accessories,0.000,383.7645,0.000,288.5820,77.658,0.0000,967.5225,684.915,...,0.0,75.054,384.468,370.125,0.000,0.0000,0.0000,95.6655,0.000,0.000
2,Mandalay,Food and beverages,1066.023,0.0000,0.000,0.0000,74.760,0.0000,374.3880,1132.005,...,0.0,0.000,0.000,0.000,0.000,0.0000,193.6305,0.0000,0.000,196.140
3,Mandalay,Health and beauty,0.000,359.2050,520.800,0.0000,0.000,760.4415,0.0000,0.000,...,0.0,0.000,0.000,435.120,0.000,0.0000,0.0000,0.0000,2059.932,1528.317
4,Mandalay,Home and lifestyle,0.000,0.0000,397.845,0.0000,334.341,261.1980,0.0000,103.110,...,0.0,0.000,0.000,629.496,0.000,116.1405,0.0000,0.0000,0.000,0.000

In [5]:
for i in range(3,len(pv_df.columns)):
    pv_df[pv_df.columns[i]] += pv_df[pv_df.columns[i-1]]

In [6]:
pv_df['Product line'].unique()

array(['Electronic accessories', 'Fashion accessories',
       'Food and beverages', 'Health and beauty', 'Home and lifestyle',
       'Sports and travel'], dtype=object)

In [7]:
img_dict = {
    'Electronic accessories': 'https://cdn-icons-png.flaticon.com/512/1233/1233183.png?w=740&t=st=1669187114~exp=1669187714~hmac=48f55b435ef680470f860ae33bb00ea3f4d532877f0ffe9d6b78629416111b9e',
    'Food and beverages': 'https://cdn-icons-png.flaticon.com/512/1255/1255229.png?w=740&t=st=1669187331~exp=1669187931~hmac=bcb2ed9d9640b8cf18f78129348c81b571c1c602a2a71fadfcb53ff2ea85ee35',
    'Health and beauty': 'https://cdn-icons-png.flaticon.com/512/1005/1005776.png?w=740&t=st=1669187487~exp=1669188087~hmac=77ba137179ee13bdc8bc7f57b342d0727f3c0085dad1f7426629dbb44e1aa099',
    'Sports and travel': 'https://cdn-icons-png.flaticon.com/512/1231/1231971.png?w=740&t=st=1669187624~exp=1669188224~hmac=1250e4dd91740db52be8cb01a1849451e4ec60c1bc078d0272e216b974e099c5',
    'Home and lifestyle': 'https://cdn-icons-png.flaticon.com/512/1198/1198316.png?w=740&t=st=1669187958~exp=1669188558~hmac=a92998c71396431b31a7b214297f3567945f0acb242b1da5cac9afe0a62a6446',
    'Fashion accessories': 'https://cdn-icons-png.flaticon.com/512/743/743015.png?w=740&t=st=1669188225~exp=1669188825~hmac=c5bf8195a95da078dfeccc573c9bad64f6282cf57c222409518c40b093ba97c9'
}

pv_df['Image'] = ''

pv_df.Image = pv_df['Product line'].apply(lambda x: img_dict[x])

In [8]:
pv_df.head()

Date,City,Product line,2019-01-01,2019-01-02,2019-01-03,2019-01-04,2019-01-05,2019-01-06,2019-01-07,2019-01-08,...,2019-03-22,2019-03-23,2019-03-24,2019-03-25,2019-03-26,2019-03-27,2019-03-28,2019-03-29,2019-03-30,Image
0,Mandalay,Electronic accessories,470.673,609.3360,609.3360,685.1145,685.1145,685.1145,685.1145,685.1145,...,16568.412,16568.412,16568.412,16790.550,16934.5365,17051.4435,17051.4435,17051.4435,17051.4435,https://cdn-icons-png.flaticon.com/512/1233/12...
1,Mandalay,Fashion accessories,0.000,383.7645,383.7645,672.3465,750.0045,750.0045,1717.5270,2402.4420,...,15563.058,15947.526,16317.651,16317.651,16317.6510,16317.6510,16413.3165,16413.3165,16413.3165,https://cdn-icons-png.flaticon.com/512/743/743...
2,Mandalay,Food and beverages,1066.023,1066.0230,1066.0230,1066.0230,1140.7830,1140.7830,1515.1710,2647.1760,...,14825.118,14825.118,14825.118,14825.118,14825.1180,15018.7485,15018.7485,15018.7485,15214.8885,https://cdn-icons-png.flaticon.com/512/1255/12...
3,Mandalay,Health and beauty,0.000,359.2050,880.0050,880.0050,880.0050,1640.4465,1640.4465,1640.4465,...,15957.291,15957.291,16392.411,16392.411,16392.4110,16392.4110,16392.4110,18452.3430,19980.6600,https://cdn-icons-png.flaticon.com/512/1005/10...
4,Mandalay,Home and lifestyle,0.000,0.0000,397.8450,397.8450,732.1860,993.3840,993.3840,1096.4940,...,16803.528,16803.528,17433.024,17433.024,17549.1645,17549.1645,17549.1645,17549.1645,17549.1645,https://cdn-icons-png.flaticon.com/512/1198/11...

In [9]:
pv_df.to_csv('supermarket.csv',index=None)